train:
  model_path: 'boston_housing/model.py'
  cloud: "local"
  cpu_count: 8
  memory_size: 16
  image_tag: ''
  project_name: "___"
  options:
    - batch_size: 1
      epoch: 5
      learning_rate: 0.0001
    - batch_size: [1, 2]
      epoch: [1]
      learning_rate: [0.001, 0.01]