train:
  model_path: 'iris_flower/model.py'
  cloud: "fast_local"
  cpu_count: 8
  memory_size: 16
  image_tag: ''
  project_name: "iris_flower"
  options:
    - batch_size: [1, 2, 5]
      epoch: [1]
      learning_rate: [0.0001, 0.01]