train:
  project_name: 'boston_housing'
  model_path: 'boston_housing/model.py'
  cloud: "fast_local"
  cpu_count: 8
  memory_size: 16
  image_tag: ''
  options:
    - batch_size: 1
      epoch: 5
      learning_rate: 0.0001